config/routes.rb
Rails.application.routes.draw do
  resources :activities

  resources :activity_categories

  resources :contacts

  devise_for :users

  get 'static_pages/contact'
  get 'about' => 'static_pages#about'
  get 'contactus' => 'static_pages#contact'

  root 'static_pages#index'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
	belongs_to :activity_category
	belongs_to :contact

	accepts_nested_attributes_for :activity_category
	accepts_nested_attributes_for :contact
end

app/models/activity_category.rb
class ActivityCategory < ActiveRecord::Base
	has_many :activities

	accepts_nested_attributes_for :activities
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	has_paper_trail
	acts_as_taggable_on :tags

	def full_name
		[name,firstname].join(" ")
	end

	def skype_link
		"skype:#{skype_uri}?call"
	end

	def lync_link
		"callto:#{lync_uri}"
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:date, :activity_category_id, :contact_id, :PlannedDate, :ProtocolText)
    end
end

app/controllers/activity_categories_controller.rb
class ActivityCategoriesController < ApplicationController
  before_action :set_activity_category, only: [:show, :edit, :update, :destroy]

  # GET /activity_categories
  # GET /activity_categories.json
  def index
    @activity_categories = ActivityCategory.all
  end

  # GET /activity_categories/1
  # GET /activity_categories/1.json
  def show
  end

  # GET /activity_categories/new
  def new
    @activity_category = ActivityCategory.new
  end

  # GET /activity_categories/1/edit
  def edit
  end

  # POST /activity_categories
  # POST /activity_categories.json
  def create
    @activity_category = ActivityCategory.new(activity_category_params)

    respond_to do |format|
      if @activity_category.save
        format.html { redirect_to @activity_category, notice: 'Activity category was successfully created.' }
        format.json { render :show, status: :created, location: @activity_category }
      else
        format.html { render :new }
        format.json { render json: @activity_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activity_categories/1
  # PATCH/PUT /activity_categories/1.json
  def update
    respond_to do |format|
      if @activity_category.update(activity_category_params)
        format.html { redirect_to @activity_category, notice: 'Activity category was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity_category }
      else
        format.html { render :edit }
        format.json { render json: @activity_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activity_categories/1
  # DELETE /activity_categories/1.json
  def destroy
    @activity_category.destroy
    respond_to do |format|
      format.html { redirect_to activity_categories_url, notice: 'Activity category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity_category
      @activity_category = ActivityCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_category_params
      params.require(:activity_category).permit(:name, :description, :is_changable)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    #@contacts = Contact.all
    @q = Contact.search(params[:q])
    @contacts = @q.result(distinct: true)
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    @version_count = @contact.versions.length + 1
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)

        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :firstname, :street, :zip, :city, :country, :tel, :email, :skype_uri, :lync_uri, :tag_list)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/activity_categories_helper.rb
module ActivityCategoriesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :activity_category_id %><br>
    <%= f.number_field :activity_category_id %>
  </div>
  <div class="field">
    <%= f.label :contact_id %><br>
    <%= f.number_field :contact_id %>
  </div>
  <div class="field">
    <%= f.label :PlannedDate %><br>
    <%= f.datetime_select :PlannedDate %>
  </div>
  <div class="field">
    <%= f.label :ProtocolText %><br>
    <%= f.text_area :ProtocolText %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<h1>Listing activities</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Activity category</th>
      <th>Contact</th>
      <th>Planneddate</th>
      <th>Protocoltext</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.date %></td>
        <td><%= activity.activity_category.name %></td>
        <td><%= activity.contact.full_name %></td>
        <td><%= activity.PlannedDate %></td>
        <td><%= activity.ProtocolText %></td>
        <td><%= link_to 'Show', activity %></td>
        <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
        <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activity', new_activity_path %>

app/views/activities/new.html.erb
<h1>New activity</h1>

<%= render 'form' %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @activity.date %>
</p>

<p>
  <strong>Activity category:</strong>
  <%= @activity.activity_category_id %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @activity.contact_id %>
</p>

<p>
  <strong>Planneddate:</strong>
  <%= @activity.PlannedDate %>
</p>

<p>
  <strong>Protocoltext:</strong>
  <%= @activity.ProtocolText %>
</p>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>

app/views/activity_categories/_form.html.erb
<%= form_for(@activity_category) do |f| %>
  <% if @activity_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity_category.errors.count, "error") %> prohibited this activity_category from being saved:</h2>

      <ul>
      <% @activity_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :is_changable %><br>
    <%= f.check_box :is_changable %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activity_categories/edit.html.erb
<h1>Editing activity_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity_category %> |
<%= link_to 'Back', activity_categories_path %>

app/views/activity_categories/index.html.erb
<h1>Listing activity_categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Is changable</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activity_categories.each do |activity_category| %>
      <tr>
        <td><%= activity_category.name %></td>
        <td><%= activity_category.description %></td>
        <td><%= activity_category.is_changable %></td>
        <td><%= link_to 'Show', activity_category %></td>
        <td><%= link_to 'Edit', edit_activity_category_path(activity_category) %></td>
        <td><%= link_to 'Destroy', activity_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activity category', new_activity_category_path %>

app/views/activity_categories/new.html.erb
<h1>New activity_category</h1>

<%= render 'form' %>

<%= link_to 'Back', activity_categories_path %>

app/views/activity_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @activity_category.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @activity_category.description %>
</p>

<p>
  <strong>Is changable:</strong>
  <%= @activity_category.is_changable %>
</p>

<%= link_to 'Edit', edit_activity_category_path(@activity_category) %> |
<%= link_to 'Back', activity_categories_path %>

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :street %><br>
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :tel %><br>
    <%= f.text_field :tel %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :skype_uri %><br>
    <%= f.text_field :skype_uri %>
  </div>
  <div class="field">
    <%= f.label :lync_uri %><br>
    <%= f.text_field :lync_uri %>
  </div>
  <div class="field">
    <%= f.label "Tag Liste" %><br>
    <%= f.text_field :tag_list %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1>Zeige alle Kunden an</h1>

<%= search_form_for @q do |f| %>
  <%= f.label :name_start %>
  <%= f.search_field :name_start %>
  <%= f.label :city_cont %>
  <%= f.search_field :city_cont %>
  <%= f.label :email_cont %>
  <%= f.search_field :email_cont %>
  <%= f.submit %>
<% end %>

<table>
  <thead>
    <tr>
      <%= content_tag :th, sort_link(@q, :name) %>
      <%= content_tag :th, sort_link(@q, :firstname) %>
      <%= content_tag :th, sort_link(@q, :street) %>
      <%= content_tag :th, sort_link(@q, :zip) %>
      <%= content_tag :th, sort_link(@q, :city) %>
      <%= content_tag :th, sort_link(@q, :country) %>
      <th>Tel</th>
      <th>Email</th>
      <th>Skype uri</th>
      <th>Lync uri</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.firstname %></td>
        <td><%= contact.street %></td>
        <td><%= contact.zip %></td>
        <td><%= contact.city %></td>
        <td><%= contact.country %></td>
        <td><%= contact.tel %></td>
        <td><%= contact.email %></td>
        <td><%= link_to 'Skype', contact.skype_link %></td>
        <td><%= link_to 'Lync', contact.lync_link %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Version Count</strong>
  <%= @version_count %>
</p>
<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @contact.firstname %>
</p>

<p>
  <strong>Street:</strong>
  <%= @contact.street %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @contact.zip %>
</p>

<p>
  <strong>City:</strong>
  <%= @contact.city %>
</p>

<p>
  <strong>Country:</strong>
  <%= @contact.country %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @contact.tel %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Skype uri:</strong>
  <%= @contact.skype_uri %>
</p>

<p>
  <strong>Lync uri:</strong>
  <%= @contact.lync_uri %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to 'Project CLEO', root_path %>
    by Cloudwerkstatt GmbH
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contactus_path %></li>
      <li><a href="#">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "project cleo", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",     root_path %></li>
          <li><%= link_to "Contacts", contacts_path %></li>
          <% if user_signed_in? %>
          <li><%= link_to current_user.email, destroy_user_session_path, :method => 'delete' %></li>
          <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>

    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'Contact') %>
<h1>About</h1>
<p>
  About Lorem Ipsum
  <a href="#">about page</a>.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/index.html.erb
<div class="center hero-unit">
  <h1>Welcome to Project CLEO!</h1>

  <h2>
    This is the home page for the
    <a href="http://www.google.at/">Project CLEO</a>
    prototype application.
  </h2>

  <%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-large btn-primary" %>
</div>